/**
 * The kit behind the send sheet and the document import.
 *
 * Both screens are about one thing — a message leaving the building — and both need the same four
 * things from it: the API contract (`/api/email/*`), the vocabulary of a block, the attachment
 * rules, and a way to say *what could not be read* rather than drawing a blank.
 *
 * ── The block vocabulary is not defined here ────────────────────────────────────────────────────────
 *
 * `EmailBlock` comes from `@C7NTAX/shared`, because the editor, the renderer and the importer must
 * agree about what a block is or a block one of them draws silently disappears from a customer's
 * email. **There is deliberately no second renderer here.** The HTML and the text of a message come
 * from `POST /api/email/preview`, so the message a person approves in this sheet is literally the
 * message that goes out; this file only *describes* blocks (a label, one line of what it carries,
 * where it came from) for the lists the sheet draws.
 *
 * ── Degrading honestly ─────────────────────────────────────────────────────────────────────────────
 *
 * The Email API is part of the same change and may not be deployed on an instance this screen is
 * opened against. Every call therefore returns a discriminated result and every failure is rendered
 * by `CallNote`, which names the endpoint and repeats the API's own words. Nothing here invents a
 * friendlier message, and nothing renders a preview it did not receive.
 */
import { isAxiosError } from "axios";
import type { ReactNode } from "react";
import api from "../../api";
import { apiErrorMessage } from "../../lib/apiError";
import { MAX_ATTACHMENT_BYTES, formatBytes } from "../richText";
import { blockKindLabel, blockToTextLines, compareTextFacts, conditionLabel, derivePlainText, htmlToText, tokensInBlock } from "./emailBlocks";
import type { EmailBlock, EmailTemplate } from "@C7NTAX/shared";

export { MAX_ATTACHMENT_BYTES, formatBytes };
export type { EmailBlock, EmailTemplate };

/**
 * The block vocabulary and the plain-text renderer belong to `emailBlocks.tsx`, which the editor, the
 * canvas and this sheet all read. This file re-exports them rather than restating them: a second
 * `blockLabel` is a second answer to what a block is called, and a second text renderer is how two
 * parts of the same message come to carry different facts.
 */
export { compareTextFacts, derivePlainText, tokensInBlock };

/** The routes this sheet calls. Named once so a rename is one change and a failure can name it. */
export const EMAIL_API = {
  messages: "/email/messages",
  preview: "/email/preview",
  send: "/email/send",
  import: "/email/import",
  /** The invoice path that already exists — it writes the status and sends nothing. */
  invoiceSend: (id: string) => `/billing/invoices/${id}/send`,
  /** The invoice document the sender attaches, generated by the API today. */
  invoicePdf: (id: string) => `/billing/invoices/${id}/pdf`,
} as const;

/** A call that did not answer, described well enough to be shown to a person. */
export interface CallFailure {
  /** The route, with its leading slash, as it appears in this file. */
  endpoint: string;
  status?: number;
  /** The API's own words when it sent any, otherwise a plain statement of what happened. */
  reason: string;
  /** Set when the failure is "this route is not on this instance" rather than a refusal. */
  absent: boolean;
}

function statusOf(error: unknown): number | undefined {
  return isAxiosError(error) ? error.response?.status : undefined;
}

export function describeFailure(endpoint: string, error: unknown): CallFailure {
  const status = statusOf(error);
  const reason = status === 404
    ? `${endpoint} is not on this instance`
    : apiErrorMessage(error, status ? `${endpoint} answered ${status}` : `${endpoint} could not be reached`);
  return { endpoint, status, reason, absent: status === 404 || status === 501 };
}

/** The API answers `{ … }` or `{ data: … }`; both are in use, so both are accepted. */
export function unwrap<T>(payload: unknown): T {
  if (payload && typeof payload === "object" && "data" in payload) {
    return (payload as { data: T }).data;
  }
  return payload as T;
}

// ── The preview, exactly as `POST /api/email/preview` returns it ─────────────

export interface EmailPreview {
  subject: string;
  html: string;
  /** The plain-text part that will be sent beside the HTML — what a client shows when it strips HTML. */
  text: string;
  /**
   * The text derived from the blocks. It is always present so the sheet can show both, and warn when
   * they carry different facts: a message read in a client that strips HTML has to be the same message.
   */
  derivedText: string;
  warnings: string[];
}

export type PreviewState =
  | { status: "loading" }
  | { status: "ready"; preview: EmailPreview }
  | { status: "failed"; failure: CallFailure };

/** Reads the preview response defensively: a field the API did not send is not invented here. */
export function readPreview(payload: unknown): EmailPreview | null {
  const body = unwrap<Record<string, unknown>>(payload);
  if (!body || typeof body !== "object") return null;
  const html = typeof body.html === "string" ? body.html : "";
  if (!html) return null;
  const text = typeof body.text === "string" ? body.text : "";
  const derivedText = typeof body.derivedText === "string" ? body.derivedText : text;
  return {
    subject: typeof body.subject === "string" ? body.subject : "",
    html,
    text,
    derivedText,
    warnings: Array.isArray(body.warnings) ? body.warnings.filter((w): w is string => typeof w === "string") : [],
  };
}

/** Replaces tags with their text. Used for a one-line description of a block, never for sending. */
export { htmlToText as blockPlainText };

// ── Describing a block ───────────────────────────────────────────────────────

/** The kind's own name, from the palette's vocabulary. */
export function blockLabel(block: EmailBlock): string {
  return blockKindLabel(block.kind);
}

/**
 * One line of what the block carries, in the words the recipient would read.
 *
 * Taken from the shared text renderer with the fields left unresolved, so the list shows the
 * template's own words — `{{ticket.number}}` rather than a value from whichever record is open.
 */
export function blockSummary(block: EmailBlock): string {
  const lines = blockToTextLines(block, (value) => value).filter((line) => line.trim().length > 0);
  return lines.join(" · ") || "an empty block";
}

/** What the block reads, so nobody wonders where a line came from: its fields, or its condition. */
export function blockReads(block: EmailBlock): string {
  const parts: string[] = [];
  const tokens = tokensInBlock(block);
  if (tokens.length) parts.push(tokens.map((token) => `{{${token}}}`).join(", "));
  if (block.kind === "conditional") parts.push(`sent only when ${conditionLabel(block.when)}`);
  if (!parts.length) parts.push("written here");
  return parts.join(" · ");
}

/** The block kinds whose own words the author may change in the sheet. */
export function isEditable(block: EmailBlock): boolean {
  return block.kind === "paragraph" || block.kind === "heading" || block.kind === "note";
}

/** A block with the author's own words in it. Only the three editable kinds take a change. */
export function withBlockText(block: EmailBlock, text: string): EmailBlock {
  switch (block.kind) {
    case "heading": return { ...block, text };
    case "paragraph": return { ...block, html: text };
    case "note": return { ...block, text };
    default: return block;
  }
}

/** The editable words of a block, or an empty string when it has none. */
export function blockText(block: EmailBlock): string {
  switch (block.kind) {
    case "heading": return block.text;
    case "paragraph": return htmlToText(block.html);
    case "note": return block.text;
    default: return "";
  }
}

/**
 * The chosen facts, applied to the catalogue's blocks.
 *
 * One state, two views — the sheet lists the same blocks twice: by *fact* (what information gets
 * sent, which is what the owner asked to choose) and by *composition* (how the message is built).
 * Both write the same set, because a second copy of the choice is a second answer to the same question.
 */
export function selectedBlocks(blocks: EmailBlock[], off: ReadonlySet<number>): EmailBlock[] {
  return blocks.filter((_, index) => !off.has(index));
}

// ── Attachments ──────────────────────────────────────────────────────────────

export interface AttachmentRef {
  /** `invoice`, `report` or a file already on the ticket — the API writes the bytes. */
  kind: "invoice" | "report" | "ticketAttachment";
  id: string;
  name: string;
  /** Billed to the message and shown to the author; never a promise — see `AttachmentRow`. */
  bytes?: number;
  why: string;
}

export interface AttachmentUpload {
  filename: string;
  mimeType: string;
  size: number;
  contentBase64: string;
}

export type AttachmentVerdict =
  | { ok: true }
  | { ok: false; reason: string; tooBig: true; bytes: number }
  | { ok: false; reason: string; tooBig?: false };

/** The same limit the ticket composer enforces, so a file that fits in the composer fits here. */
export function checkAttachment(file: File): AttachmentVerdict {
  if (file.size > MAX_ATTACHMENT_BYTES) {
    return { ok: false, tooBig: true, bytes: file.size, reason: `${file.name} is ${formatBytes(file.size)} — over the ${formatBytes(MAX_ATTACHMENT_BYTES)} limit` };
  }
  return { ok: true };
}

// ── Small pieces both arrangements use ───────────────────────────────────────

/**
 * The switch. Shared deliberately: a control's *shape* is the shared kit's business, and the two
 * interfaces differ in how the switch is arranged and what is written beside it, not in what it is.
 */
export function Switch({
  on, onToggle, disabled, label,
}: {
  on: boolean;
  onToggle: (next: boolean) => void;
  disabled?: boolean;
  label: string;
}) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={on}
      aria-label={label}
      disabled={disabled}
      onClick={() => onToggle(!on)}
      className={`inline-flex h-5 w-9 shrink-0 items-center rounded-full border transition-colors disabled:cursor-not-allowed disabled:opacity-40 ${
        on ? "border-cyber-500 bg-cyber-600/25" : "border-surface-border bg-surface-lighter"
      }`}
    >
      <span
        className={`mx-0.5 h-3.5 w-3.5 rounded-full transition-transform ${
          on ? "translate-x-4 bg-cyber-400" : "bg-gray-500"
        }`}
      />
    </button>
  );
}

/**
 * A call that did not answer, named.
 *
 * This is the whole of the "degrade honestly" rule in one place: the route, the API's own words, and
 * whether the route is simply not on this instance. Nothing here says "something went wrong".
 */
export function CallNote({ failure, what }: { failure: CallFailure; what: string }) {
  return (
    <div className="flex items-start gap-2.5 rounded-lg border border-surface-border bg-surface-light p-3">
      <span className="mt-0.5 text-alert-amber" aria-hidden>▲</span>
      <div className="min-w-0">
        <p className="text-xs text-white">{what}</p>
        <p className="mt-1 font-mono text-[11px] text-gray-400">{failure.endpoint}</p>
        <p className="mt-1 text-xs text-gray-400">{failure.reason}</p>
        {failure.absent && (
          <p className="mt-1 text-[11px] text-gray-500">
            Nothing is drawn from a route that is not there: the sheet names what it could not read
            rather than showing an empty preview.
          </p>
        )}
      </div>
    </div>
  );
}

/**
 * The message as the recipient will receive it.
 *
 * An iframe with an empty `sandbox`: the HTML is the API's, inline-styled, and it must not inherit
 * this application's stylesheet, its theme or its colour scheme — a preview that borrows the app's
 * CSS is a picture of the app, not of the message. `srcDoc` never scripts anything (the sanitiser
 * has already dropped `script`, `style`, `iframe` and every `on*` handler), and the sandbox makes
 * that a property of the frame rather than a promise about the string.
 */
export function PreviewFrame({ html, title, className = "" }: { html: string; title: string; className?: string }) {
  return (
    <iframe
      title={title}
      sandbox=""
      srcDoc={html}
      className={`w-full rounded-lg border border-surface-border bg-surface-light ${className}`}
    />
  );
}

/**
 * The plain-text part, beside the HTML.
 *
 * The owner asked for this in so many words: some mail systems strip the HTML out, so the message
 * has to be readable anyway. This is not a description of the text part — it is the text part, the
 * one that travels in the `multipart/alternative` body beside the HTML.
 */
export function TextPane({ text, className = "" }: { text: string; className?: string }) {
  return (
    <pre
      className={`max-h-80 overflow-auto whitespace-pre-wrap rounded-lg border border-surface-border bg-surface-light p-3 font-mono text-[11px] leading-relaxed text-gray-300 ${className}`}
    >
      {text || "The text part is empty."}
    </pre>
  );
}

/** Both parts, and the fact that both are going: one sentence, in both arrangements. */
export function BothPartsNote({ agree }: { agree: boolean | null }) {
  return (
    <p className="text-[11px] text-gray-500">
      Both parts are sent: <span className="text-gray-300">multipart/alternative</span> carries the HTML
      and this text beside it, so a client that strips HTML still reads the same facts.{" "}
      {agree === null
        ? "There is no HTML from the renderer to compare with yet, so nothing is claimed about the two agreeing."
        : agree
          ? "Here the two agree — the text part is the text of the blocks."
          : "Here they differ — the text part is the one this message will actually be read as."}
    </p>
  );
}

/** A glyph tile for a panel heading. Token-only, and it follows the accent like every other tile. */
export function Tile({ children, tone = "cyber" }: { children: ReactNode; tone?: "cyber" | "amber" | "green" | "neutral" }) {
  const tones: Record<string, string> = {
    cyber: "bg-cyber-600/15 text-cyber-400",
    amber: "bg-amber-500/15 text-amber-400",
    green: "bg-emerald-500/15 text-emerald-400",
    neutral: "bg-surface-lighter text-gray-300",
  };
  return <span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-lg ${tones[tone]}`}>{children}</span>;
}
