import { useState, useEffect } from "react";
import api from "../api";
import toast from "react-hot-toast";
import { Save, Eye, Copy, FileText, Bold, Italic, Underline, List, ListOrdered, Heading1, Heading2, Table, Download, RefreshCw, Plus } from "lucide-react";

interface Template {
  id: string; name: string; description: string;
  content: string; category: string;
}

const SAMPLE_TEMPLATES: Template[] = [
  {
    id: "ticket-summary", name: "Ticket Summary Report", category: "Tickets",
    description: "Overview of ticket volume, status distribution, priority breakdown, and aging summary.",
    content: `<h2>Ticket Summary Report</h2>
<p><em>Generated: {{date}}</em></p>

<h3>Overview</h3>
<table>
<thead><tr><th>Metric</th><th>Value</th></tr></thead>
<tbody>
<tr><td>Total Tickets</td><td>{{total_tickets}}</td></tr>
<tr><td>Open</td><td>{{open_tickets}}</td></tr>
<tr><td>In Progress</td><td>{{in_progress}}</td></tr>
<tr><td>Waiting on Client</td><td>{{waiting_client}}</td></tr>
<tr><td>On Hold</td><td>{{on_hold}}</td></tr>
<tr><td>Resolved (30d)</td><td>{{resolved_30d}}</td></tr>
</tbody>
</table>

<h3>Priority Distribution</h3>
<table>
<thead><tr><th>Priority</th><th>Count</th></tr></thead>
<tbody>
<tr><td>Critical</td><td>{{critical_count}}</td></tr>
<tr><td>High</td><td>{{high_count}}</td></tr>
<tr><td>Medium</td><td>{{medium_count}}</td></tr>
<tr><td>Low</td><td>{{low_count}}</td></tr>
</tbody>
</table>

<h3>Ticket Aging</h3>
<ul>
<li>&lt; 1 day: {{age_1d}}</li>
<li>1-3 days: {{age_3d}}</li>
<li>3-7 days: {{age_7d}}</li>
<li>7-30 days: {{age_30d}}</li>
<li>&gt; 30 days: {{age_over}}</li>
</ul>

<p><strong>Note:</strong> This report was auto-generated by C7NTAX Reporting.</p>`
  },
  {
    id: "project-profitability", name: "Project Profitability", category: "Financial",
    description: "Revenue vs cost analysis per project with margin calculations.",
    content: `<h2>Project Profitability Report</h2>
<p><em>Period: {{date_from}} to {{date_to}}</em></p>

<h3>Project Financial Summary</h3>
<table>
<thead><tr><th>Project</th><th>Budget</th><th>Revenue</th><th>Cost</th><th>Margin</th><th>Margin %</th></tr></thead>
<tbody>
<tr><td>{{project_name_1}}</td><td>${{budget_1}}</td><td>${{revenue_1}}</td><td>${{cost_1}}</td><td>${{margin_1}}</td><td>{{margin_pct_1}}%</td></tr>
<tr><td>{{project_name_2}}</td><td>${{budget_2}}</td><td>${{revenue_2}}</td><td>${{cost_2}}</td><td>${{margin_2}}</td><td>{{margin_pct_2}}%</td></tr>
</tbody>
</table>

<h3>Key Findings</h3>
<ul>
<li>Total Revenue: ${{total_revenue}}</li>
<li>Total Cost: ${{total_cost}}</li>
<li>Overall Margin: {{overall_margin}}%</li>
<li>Most Profitable Project: {{top_project}}</li>
</ul>`
  },
  {
    id: "time-entries", name: "Time Entry Report", category: "Time",
    description: "Detailed time tracking with billable vs non-billable breakdown.",
    content: `<h2>Time Entry Report</h2>
<p><em>Period: {{date_from}} to {{date_to}}</em></p>

<h3>Time Summary</h3>
<table>
<thead><tr><th>Technician</th><th>Billable Hours</th><th>Non-Billable</th><th>Total Hours</th><th>Utilization</th></tr></thead>
<tbody>
{{technician_rows}}
</tbody>
</table>

<h3>Totals</h3>
<ul>
<li>Total Billable: {{total_billable}} hours</li>
<li>Total Non-Billable: {{total_non_billable}} hours</li>
<li>Overall Utilization: {{overall_utilization}}%</li>
</ul>`
  },
  {
    id: "sla-compliance", name: "SLA Compliance Report", category: "Performance",
    description: "Service level agreement response and resolution compliance tracking.",
    content: `<h2>SLA Compliance Report</h2>
<p><em>Generated: {{date}}</em></p>

<h3>Response SLA</h3>
<table>
<thead><tr><th>Metric</th><th>Count</th><th>Percentage</th></tr></thead>
<tbody>
<tr><td>Met Response SLA</td><td>{{met_response}}</td><td>{{met_response_pct}}%</td></tr>
<tr><td>Breached Response SLA</td><td>{{breached_response}}</td><td>{{breached_response_pct}}%</td></tr>
</tbody>
</table>

<h3>Resolution SLA</h3>
<table>
<thead><tr><th>Metric</th><th>Count</th><th>Percentage</th></tr></thead>
<tbody>
<tr><td>Met Resolution SLA</td><td>{{met_resolution}}</td><td>{{met_resolution_pct}}%</td></tr>
<tr><td>Breached Resolution SLA</td><td>{{breached_resolution}}</td><td>{{breached_resolution_pct}}%</td></tr>
</tbody>
</table>

<h3>Recommendations</h3>
<p>Based on the SLA data above, the following actions are recommended:</p>
<ul>
<li>Review breached tickets for root cause analysis</li>
<li>Adjust SLA targets if consistently missed</li>
<li>Provide additional training for high-breach categories</li>
</ul>`
  },
  {
    id: "revenue", name: "Revenue & Billing Report", category: "Financial",
    description: "Monthly revenue summary, outstanding invoices, and collection metrics.",
    content: `<h2>Revenue & Billing Report</h2>
<p><em>Generated: {{date}}</em></p>

<h3>Financial Overview</h3>
<table>
<thead><tr><th>Metric</th><th>Amount</th></tr></thead>
<tbody>
<tr><td>Total Invoiced</td><td>${{total_invoiced}}</td></tr>
<tr><td>Total Collected</td><td>${{total_collected}}</td></tr>
<tr><td>Outstanding</td><td>${{outstanding}}</td></tr>
<tr><td>Overdue</td><td>${{overdue}}</td></tr>
<tr><td>Collection Rate</td><td>{{collection_rate}}%</td></tr>
</tbody>
</table>

<h3>Monthly Revenue Trend</h3>
{{monthly_revenue_table}}

<h3>Top 5 Clients by Revenue</h3>
{{top_clients_table}}`
  },
];

function renderPreview(html: string): string {
  const now = new Date().toLocaleDateString();
  const vars: Record<string, string> = {
    date: now, date_from: "2026-01-01", date_to: now,
    total_tickets: "8", open_tickets: "5", in_progress: "3", waiting_client: "1", on_hold: "0", resolved_30d: "2",
    critical_count: "1", high_count: "3", medium_count: "3", low_count: "1",
    age_1d: "2", age_3d: "1", age_7d: "1", age_30d: "1", age_over: "0",
    project_name_1: "Acme Migration", budget_1: "15,000", revenue_1: "18,500", cost_1: "12,000", margin_1: "6,500", margin_pct_1: "35",
    project_name_2: "Globex Firewall", budget_2: "35,000", revenue_2: "42,000", cost_2: "28,000", margin_2: "14,000", margin_pct_2: "33",
    total_revenue: "60,500", total_cost: "40,000", overall_margin: "34", top_project: "Globex Firewall",
    technician_rows: "<tr><td>John Smith</td><td>24.5</td><td>3.0</td><td>27.5</td><td>89%</td></tr><tr><td>Sarah Jones</td><td>18.0</td><td>5.5</td><td>23.5</td><td>77%</td></tr>",
    total_billable: "42.5", total_non_billable: "8.5", overall_utilization: "83",
    met_response: "6", met_response_pct: "75", breached_response: "2", breached_response_pct: "25",
    met_resolution: "4", met_resolution_pct: "67", breached_resolution: "2", breached_resolution_pct: "33",
    total_invoiced: "15,180", total_collected: "2,712", outstanding: "12,468", overdue: "3,788", collection_rate: "18",
    monthly_revenue_table: "<table><thead><tr><th>Month</th><th>Revenue</th></tr></thead><tbody><tr><td>2026-07</td><td>$2,712</td></tr><tr><td>2026-06</td><td>$5,430</td></tr></tbody></table>",
    top_clients_table: "<table><thead><tr><th>Client</th><th>Revenue</th></tr></thead><tbody><tr><td>Stark Enterprises</td><td>$13,050</td></tr><tr><td>Globex Industries</td><td>$8,680</td></tr></tbody></table>",
  };
  return html.replace(/\{\{(\w+)\}\}/g, (_, key) => vars[key] || `{{${key}}}`);
}

export function CustomReportBuilder() {
  const [templates] = useState<Template[]>(SAMPLE_TEMPLATES);
  const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(null);
  const [content, setContent] = useState("");
  const [reportName, setReportName] = useState("");
  const [showPreview, setShowPreview] = useState(true);
  const [saving, setSaving] = useState(false);

  const selectTemplate = (t: Template) => {
    setSelectedTemplate(t);
    setContent(t.content);
    setReportName(t.name);
  };

  const insertTag = (tag: string) => {
    const ta = document.getElementById("report-editor") as HTMLTextAreaElement;
    if (!ta) return;
    const start = ta.selectionStart;
    const end = ta.selectionEnd;
    setContent(content.slice(0, start) + tag + content.slice(end));
    setTimeout(() => { ta.focus(); ta.selectionStart = ta.selectionEnd = start + tag.length; }, 50);
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      await api.post("/reports", { name: reportName || "Custom Report", description: selectedTemplate?.description || "", type: "custom", config: { content, template: selectedTemplate?.id } });
      toast.success("Report saved");
    } catch { toast.error("Failed to save"); }
    finally { setSaving(false); }
  };

  const handleExport = () => {
    const w = window.open("", "_blank", "width=900,height=700")!;
    w.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${reportName}</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#fff;color:#1e293b;padding:32px}h2{border-bottom:2px solid #22d3ee;padding-bottom:8px;margin-bottom:16px}table{width:100%;border-collapse:collapse;margin:12px 0}th,td{padding:8px;border:1px solid #e2e8f0;text-align:left}th{background:#f1f5f9}ul{padding-left:20px;margin:8px 0}@media print{body{padding:16px}}</style></head><body>${renderPreview(content)}</body></html>`);
    w.document.close();
    setTimeout(() => w.print(), 500);
  };

  const previewHTML = renderPreview(content);

  return (
    <div className="space-y-4 animate-fade-in max-w-7xl">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div><h2 className="text-lg font-semibold text-white">Custom Report Builder</h2><p className="text-sm text-gray-400">{selectedTemplate ? `Editing: ${reportName}` : "Select a template or create from scratch"}</p></div>
        <div className="flex items-center gap-2">
          <button onClick={handleSave} disabled={saving} className="btn-primary text-sm flex items-center gap-1.5"><Save size={14} />{saving ? "Saving..." : "Save"}</button>
          <button onClick={handleExport} className="btn-secondary text-sm flex items-center gap-1.5"><Download size={14} />Export</button>
          <button onClick={() => setShowPreview(!showPreview)} className="btn-secondary text-sm flex items-center gap-1.5"><Eye size={14} />{showPreview ? "Hide" : "Show"} Preview</button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-4">
        {/* Template Panel */}
        <div className="card space-y-3 lg:h-[calc(100vh-200px)] lg:overflow-y-auto">
          <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider">Templates</h3>
          <p className="text-xs text-gray-500">Select a template to start your report.</p>
          <div className="space-y-2">
            <button onClick={() => { setSelectedTemplate(null); setContent("<h2>New Report</h2>\n<p>Start writing your report here...</p>"); setReportName("New Report"); }} className={`w-full text-left p-2.5 rounded-lg text-xs transition-colors border border-dashed ${!selectedTemplate ? "border-cyber-500/40 bg-cyber-600/10 text-cyber-400" : "border-surface-border text-gray-400 hover:border-cyber-500/30"}`}><Plus size={12} className="inline mr-1"/>Blank Report</button>
            {templates.map(t => (
              <button key={t.id} onClick={() => selectTemplate(t)} className={`w-full text-left p-2.5 rounded-lg text-xs transition-colors border ${selectedTemplate?.id === t.id ? "border-cyber-500/40 bg-cyber-600/10 text-cyber-400" : "border-surface-border text-gray-400 hover:border-cyber-500/30"}`}>
                <p className="font-medium text-white">{t.name}</p>
                <p className="text-gray-500 mt-0.5">{t.description.slice(0, 60)}...</p>
                <span className="badge bg-surface-lighter text-gray-500 text-[10px] mt-1">{t.category}</span>
              </button>
            ))}
          </div>

          {/* Variable Tags */}
          <div className="pt-3 border-t border-surface-border">
            <h4 className="text-xs font-semibold text-gray-500 uppercase mb-2">Insert Variable</h4>
            <div className="flex flex-wrap gap-1">
              {["{{date}}","{{total_tickets}}","{{open_tickets}}","{{critical_count}}","{{total_billable}}","{{overall_margin}}","{{total_invoiced}}","{{collection_rate}}"].map(tag => (
                <button key={tag} onClick={() => insertTag(tag)} className="text-[10px] bg-surface-lighter hover:bg-cyber-600/20 text-gray-400 hover:text-cyber-400 rounded px-1.5 py-0.5 font-mono transition-colors">{tag}</button>
              ))}
            </div>
          </div>
        </div>

        {/* Editor Panel */}
        <div className={`card space-y-3 ${showPreview ? "lg:col-span-2" : "lg:col-span-3"}`}>
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider">Editor</h3>
            <div className="flex items-center gap-0.5">
              <input className="input-field text-sm py-1 w-48" placeholder="Report name..." value={reportName} onChange={e => setReportName(e.target.value)} />
            </div>
          </div>

          {/* Formatting Toolbar */}
          <div className="flex items-center gap-0.5 flex-wrap border-b border-surface-border pb-2">
            <ToolBtn icon={Bold} tag="<strong>" endTag="</strong>" label="Bold" onClick={insertTag} />
            <ToolBtn icon={Italic} tag="<em>" endTag="</em>" label="Italic" onClick={insertTag} />
            <ToolBtn icon={Underline} tag="<u>" endTag="</u>" label="Underline" onClick={insertTag} />
            <span className="w-px h-5 bg-surface-border mx-1" />
            <ToolBtn icon={Heading1} tag="<h2>" endTag="</h2>" label="Heading" onClick={insertTag} />
            <ToolBtn icon={Heading2} tag="<h3>" endTag="</h3>" label="Subheading" onClick={insertTag} />
            <span className="w-px h-5 bg-surface-border mx-1" />
            <ToolBtn icon={List} tag="<ul>\n<li>" endTag="</li>\n</ul>" label="Bullet List" onClick={insertTag} />
            <ToolBtn icon={ListOrdered} tag="<ol>\n<li>" endTag="</li>\n</ol>" label="Numbered List" onClick={insertTag} />
            <ToolBtn icon={Table} tag={`<table>\n<thead><tr><th>Column 1</th><th>Column 2</th></tr></thead>\n<tbody>\n<tr><td>Data</td><td>Data</td></tr>\n</tbody>\n</table>`} endTag="" label="Table" onClick={insertTag} />
          </div>

          <textarea
            id="report-editor"
            className="input-field font-mono text-sm min-h-[400px] resize-y"
            value={content}
            onChange={e => setContent(e.target.value)}
            placeholder="Start writing your report HTML here... Use the toolbar buttons to insert formatting. Use {{variable}} for dynamic data."
            spellCheck={false}
          />
        </div>

        {/* Preview Panel */}
        {showPreview && (
          <div className="card lg:h-[calc(100vh-200px)] lg:overflow-y-auto">
            <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">Preview</h3>
            <div
              className="prose prose-invert prose-sm max-w-none text-gray-300 [&_h2]:text-white [&_h2]:border-b [&_h2]:border-cyber-500/30 [&_h2]:pb-1 [&_h3]:text-gray-200 [&_table]:w-full [&_table]:border-collapse [&_th]:border [&_th]:border-surface-border [&_th]:p-2 [&_th]:bg-surface-lighter [&_th]:text-left [&_td]:border [&_td]:border-surface-border [&_td]:p-2 [&_ul]:pl-5 [&_ol]:pl-5 [&_em]:text-gray-400"
              dangerouslySetInnerHTML={{ __html: previewHTML }}
            />
          </div>
        )}
      </div>
    </div>
  );
}

function ToolBtn({ icon: Icon, tag, endTag, label, onClick }: { icon: React.ComponentType<{ size?: number }>; tag: string; endTag: string; label: string; onClick: (tag: string) => void }) {
  return (
    <button
      onClick={() => onClick(endTag ? tag + (endTag.includes("\n") ? "" : "") + endTag : tag)}
      className="p-1.5 text-gray-400 hover:text-white hover:bg-surface-lighter rounded transition-colors"
      title={label}
    >
      <Icon size={14} />
    </button>
  );
}
